name: Build & deploy
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 24.x

      - name: Build app
        run: |
          yarn install
          yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mittwald/cli
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v5
      with:
        name: build
    - name: Deploy private key
      run: |
        mkdir -p /root/.ssh
        echo "${{ secrets.MITTWALD_SSH_PRIVATE_KEY_B64 }}" | base64 -d > /root/.ssh/deploy
        chmod 600 /root/.ssh/deploy
    - name: Install rsync
      run: |
        apt-get update
        apt-get install -y rsync openssh-client
    - name: Populate known hosts
      run: |
        echo 'ssh.gestringen.project.host ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv2Ojw4TM0+jFyxUgd9EzAAb8mXIzG24yS4V0Md7yphrl9vgZOyEKFhy8KfXAN1qnT1lMQKwfRqthVnfQbbSBGLSrwF1ecbnNtcXX5eAPIP7ycI+PAJJsLmV2099DpXEh9bOrf+vai29OBwtrq1ukFXatocJbC4nKSPWaFuC6yPcgqTTGMZM3ZxVhl6ONtWyao/IoGgTIHiPGxvKqcmqYYU8Zs6VSnYqQ0Sp+v1S5lgECZsDZf+EvBUe53QW8hzqm7z54ef4Qwhn13ODXU7L75LbfKbe0NJdz5higqaiz9BuIMjfbOsBHSTau5suP5fg/3nWsB3KTjl+P1B4Ipow53' >> /root/.ssh/known_hosts
    - name: Upload to mittwald
      run: |
        /app/mw/bin/mw app upload --source=. ${{ vars.MITTWALD_APP_ID }}
      env:
        MITTWALD_API_TOKEN: ${{ secrets.MITTWALD_API_TOKEN }}
        MITTWALD_SSH_USER: ${{ vars.MITTWALD_SSH_USER }}
        MITTWALD_SSH_IDENTITY_FILE: /root/.ssh/deploy