name: Build & deploy
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 24.x

      - name: Build app
        run: |
          yarn install
          yarn build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: gh-pages
          keep_history: true
          build_dir: build
          committer: Helmich-Bot <github-bot@helmich.me>
          fqdn: typo3buch.helmich.me
        env:
          GH_PAT: ${{ secrets.TOKEN }}