name: Build & deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build app
        run: |
          yarn install
          yarn build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          keep_history: true
          build_dir: build
          committer_name: Helmich-Bot
          committer_email: github-bot@helmich.me
          fqdn: typo3buch.helmich.me
        env:
          GITHUB_TOKEN: ${{ secrets.token }}